### ISSUE TITLE
nats broker?

### ISSUE THREAD

**Issue by max107** [spiral/jobs#52]

**Comment by max107** [comment]
@48d90782 А можно не закрывать ишью без объяснения? Спасибо.

**Comment by 48d90782** [comment]
@max107 Можно, но тогда сделай пожалуйста описание) Если это просто вопрос, а не Feature Request, то в репозитории RoadRunner, уже есть RFC, где можно все обсудить [link](https://github.com/spiral/roadrunner/issues/315).

**Comment by max107** [comment]
Оп, спасибо за ссылочку, подписался.
