### ISSUE TITLE
Wrong dependency for PHP8.0

### ISSUE THREAD

**Issue by lyssar** [spiral/jobs#57]
Hi there, 
I found a little issue while trying to require spiral/jobs with php ^8.0:

```
spiral/jobs[v2.2.0, ..., v2.2.1] require spiral/roadrunner ^1.1 -> found spiral/roadrunner[v1.1.0, ..., v1.9.2] but it conflicts with your root composer.json require (^2.0).
```

But in order to use `spiral/roadrunner` with php ^8.0 I need the version ^2.0 of it. So I think there is a wrong version requirement in you composer?

**Comment by 48d90782** [comment]
@lyssar Hey. The jobs plugin is not updated to 2.0. Will be released a little bit later.

**Comment by lyssar** [comment]
Oh okay. Thank you for your information :)
Is there a time when you plan to release? Or still tbd?

**Comment by 48d90782** [comment]
We are going to use totally transparent release cycles, but this issue still hasn't been scheduled. To track, please refer to this board: https://github.com/orgs/spiral/projects/2. It will be filled with tickets very soon. Thanks for the report 👍🏻

**Comment by karbowiak** [comment]
Hello there, has there been any updates to this, i'm currently running into the same issue - and don't truly feel like downgrading RR to 1.x after everything is running with 2.x :)

**Comment by SerafimArts** [comment]
@karbowiak hello! This plugin is not currently supported by the RR 2.x.
